repos:
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args: [--keep-runtime-typing]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
      args: ["--profile", "black"]
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        additional_dependencies: ['click<8.1.0']
  - repo: https://github.com/python-poetry/poetry
    rev: 1.5.1
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["--dev", "-f", "requirements.txt", "-o", "requirements.txt"]
