[build-system]
requires = ["setuptools >= 61.2"]
build-backend = "setuptools.build_meta"

[project]
name = "auth0-python"
description = "Auth0 Python SDK"
authors = [{ name = "Auth0", email = "support@auth0.com" }]
license = { text = "MIT" }
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
]
requires-python = ">=3.7"
dependencies = [
  "aiohttp >= 3.8.5, < 4",
  "pyjwt >= 2.5.0, < 3",
  "cryptography >= 41.0.3, < 42", # PyJWT has loose dependency. We want the latest one.
  "pyOpenSSL >= 23.2.0, < 24",    # pyOpenSSL 23.2.0 is required to work with cryptography 41+
  "requests >= 2.31.0, < 3",
]
dynamic = ["version"]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.optional-dependencies]
develop = [
  "sphinx",
  "aioresponses",
  "black",
  "callee",
  "flake8",
  "isort",
  "mock",
  "pre-commit",
  "pytest",
  "pytest-aiohttp",
  "pytest-cov",
  "pyupgrade",
  "responses",
  "sphinx-mdinclude",
  "sphinx-rtd-theme",
]

[tool.setuptools]
license-files = ["LICENSE"]
include-package-data = true

[tool.setuptools.packages]
find = { namespaces = false }

[tool.setuptools.package-data]
auth0 = ["py.typed"]

[tool.setuptools.dynamic]
version = { attr = "auth0.__version__" }

[project.urls]
Homepage = "https://github.com/auth0/auth0-python"
